v1
teeleontee/currency-bot pull request #1
Opened 2023-02-12 15:49 UTC by teeleontee

2023-02-21 12:59 UTC, FireF0xIl requested changes
Делать логги в консоль это конечно хорошо, но кажется писать их в файлик надежнее

2023-02-27 11:54 UTC, FireF0xIl approved these changes

2023-02-27 11:54 UTC, FireF0xIl commented on src/main/kotlin/bot/messages/Messages.kt
> +                }
`forEach` добавляет лишнюю запятую. Это можно исправить воспользовавшись `joinToString`

2023-02-27 11:54 UTC, FireF0xIl commented on src/main/kotlin/bot/handler/Handler.kt
>              }
Кажется, что логичнее было бы поставить уведомление просто на следующий день

2023-02-27 11:54 UTC, FireF0xIl commented on src/main/kotlin/bot/handler/Handler.kt
>                  sb.append(System.lineSeparator())
Кажется, что это можно было бы сделать красивее с помощью `joinToString`

2023-02-27 13:45 UTC, teeleontee commented on src/main/kotlin/bot/messages/Messages.kt
> +                }
да, не знал о таком методе

2023-02-27 13:50 UTC, merged